services:
 elasticsearch:
   image: elasticsearch:${STACK_VERSION}
   labels:
     co.elastic.logs/module: elasticsearch
   ports:
     - ${ES_PORT}:9200
   environment:
     - node.name=es01
     - cluster.name=${CLUSTER_NAME}
     - discovery.type=single-node
     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
     - bootstrap.memory_lock=true
   mem_limit: ${ES_MEM_LIMIT}
   ulimits:
     memlock:
       soft: -1
       hard: -1

 logstash:
   build: 
     dockerfile: ./dockerfile_logstash
   depends_on:
     - elasticsearch

 kibana:
   image: kibana:${STACK_VERSION}
   volumes:
     - "./kibana.yaml:/usr/share/kibana/config/kibana.yml:ro"
   ports:
     - ${KIBANA_PORT}:5601
   depends_on:
     - elasticsearch
