version: '3.7'
services:
  elastic:
    image: elasticsearch:8.11.0
    environment:
      node.name: node1
      ELASTIC_USERNAME: "admin"      
      ELASTIC_PASSWORD: "123"        
      discovery.type: single-node    
      ES_JAVA_OPTS: -Xms512m -Xmx512m 
    networks:
      - elas                      
    ports:
      - "9200:9200"
      - "9300:9300"
    
  logstash:
    image: logstash:8.11.0
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    depends_on: 
      - elastic
    networks:
      - elas
    ports: 
      - "5044:5044"
      - "9600:9600"
      
  kibana:
    image: kibana:8.11.0 
    networks:
      - elas
    ports:
      - "5601:5601"
      
networks:
   elas:
     driver: bridge  
  