services:
 elasticsearch:
   image: elasticsearch:${STACK_VERSION}
   labels:
     co.elastic.logs/module: elasticsearch
   ports:
     - ${ES_PORT}:9200
   environment:
     - node.name=es01
     - cluster.name=${CLUSTER_NAME}
     - discovery.type=single-node
     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
     - bootstrap.memory_lock=true
   mem_limit: ${ES_MEM_LIMIT}
   ulimits:
     memlock:
       soft: -1
       hard: -1

 logstash:
   image: logstash:${STACK_VERSION}
   volumes:
            - "./logstash.conf:/usr/share/logstash/config/logstash.conf:ro"
   ports:
     - "5044:5044"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: "-Xmx512m -Xms512m"
   depends_on:
     - elasticsearch

 kibana:
   image: kibana:${STACK_VERSION}
   volumes:
     - "./kibana.yaml:/usr/share/kibana/config/kibana.yml:ro"
   ports:
     - ${KIBANA_PORT}:5601
   depends_on:
     - elasticsearch
